### PR TITLE
Update Contributing Guide

### PR DESCRIPTION
**Pull request by alayek**

### CODE REVIEW

**Comment by koustuvsinha** [comment]
# LGTM :+1:

Also file the same one for `python-solution`

**Comment by erictleung** [comment]
Any idea why this is failing Travis? It says it can't find the `.travis.yml` file but it's clearly in the root of the repo.

**Comment by koustuvsinha** [comment]
@erictleung this is an old PR, our development plan has changed since then. I think it will be best if we close this one, @alayek ?

**Comment by alayek** [comment]
Yes, this should be closed. I will open a separate PR for this.

**Pull request closed without merging**
